package pt.isel.model;

import com.sun.istack.NotNull;
import jakarta.persistence.*;


/**
 *     id          INT         PRIMARY KEY
 *         GENERATED BY DEFAULT AS IDENTITY,
 *     username    VARCHAR(50) NOT NULL,
 *     email       EMAIL       NOT NULL,
 *     estado      VARCHAR(20) DEFAULT 'Ativo',
 *     nome_regiao VARCHAR(50) NOT NULL REFERENCES regiao(nome),
 */

@Entity
@Table(name="jogador",
        uniqueConstraints = {
            @UniqueConstraint(columnNames = "username"),
            @UniqueConstraint(columnNames = "email"),
            //@UniqueConstraint(columnNames = {"username", "email"})
        }
)

public class Jogador {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    @NotNull
    @Column(name = "username", nullable = false)
    private String username;

    @NotNull
    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "estado", columnDefinition = "VARCHAR(20) DEFAULT 'Ativo'")
    private String estado;

    @NotNull
    @Column(name = "nome_regiao", nullable = false)
    private String nomeRegiao;
}

