package pt.isel.model.classImp;

import com.sun.istack.NotNull;
import jakarta.persistence.*;
import pt.isel.model.Player;
import pt.isel.model.PlayerStats;
import pt.isel.model.types.Email;


/**
 * id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 *
 * username VARCHAR(50) NOT NULL,
 *
 * email EMAIL NOT NULL,
 *
 * estado VARCHAR(20) DEFAULT 'Ativo',
 *
 * nome_regiao VARCHAR(50) NOT NULL REFERENCES regiao(nome) ON DELETE CASCADE,
 *
 * UNIQUE(username),
 *
 * UNIQUE(email),
 *
 * UNIQUE(username, email),
 *
 * CONSTRAINT estado_jogador CHECK(estado ~* '^(ativo|banido|inativo)$')
 */

@Entity
@NamedQuery(name = "Jogador.findByKey", query = "SELECT j FROM Jogador j where j.id = :id")
@NamedQuery(name = "Jogador.findByUsername", query = "SELECT j FROM Jogador j where j.username = :username")
@NamedStoredProcedureQuery(
        name = "Jogador.updateEstado",
        procedureName = "update_estado_jogador",
        parameters = {
                @StoredProcedureParameter(mode = ParameterMode.IN, name = "username", type = String.class),
                @StoredProcedureParameter(mode = ParameterMode.IN, name = "estado", type = String.class)
        }
)
@Table(name="jogador", schema = "public")
public class Jogador implements Player {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    @NotNull
    @Column(name = "username", nullable = false, unique = true)
    private String username;

    @NotNull
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    @Column(name = "estado", columnDefinition = "VARCHAR(20) DEFAULT 'Ativo'")
    private String estado;

    @NotNull
    @Column(name = "nome_regiao", nullable = false)
    private String nomeRegiao;

    @OneToOne(mappedBy = "jogador")
    private JogadorEstatistica estatistica;

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public String getUserName() {
        return this.username;
    }

    @Override
    public Email getEmail() {
        return new Email(this.email);
    }

    @Override
    public String getEstado() {
        return this.estado;
    }

    @Override
    public String getNomeRegiao() {
        return this.nomeRegiao;
    }

    @Override
    public void setUserName(String userName) {
        this.username = userName;
    }

    @Override
    public void setEmail(Email email) {
        this.email = email.toString();
    }

    @Override
    public void setEstado(String estado) {
        if(estado.matches("^(ativo|banido|inativo)$"))
            this.estado = estado;
        else
            throw new IllegalArgumentException("Estado inválido");
    }

    @Override
    public void setNomeRegiao(String nomeRegiao) {
        this.nomeRegiao = nomeRegiao;
    }

    @Override
    public JogadorEstatistica getJogadorEstatistica() {
        return this.estatistica;
    }

    @Override
    public void setJogadorEstatistica(PlayerStats estatistica) {
        this.estatistica = (JogadorEstatistica) estatistica;
    }

    @Override
    public boolean isValid() {
        return false;
    }

    // Constructors
    public Jogador() {
    }

    public Jogador(String username, Email email, String estado, String nomeRegiao) {
        setUserName(username);
        setEmail(email);
        setEstado(estado);
        setNomeRegiao(nomeRegiao);
    }

    @Override
    public String toString() {
        return "Jogador{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", estado='" + estado + '\'' +
                ", nomeRegiao='" + nomeRegiao + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Jogador)) return false;
        Jogador jogador = (Jogador) o;
        return username.equals(jogador.username) && email.equals(jogador.email);
    }

    @Override
    public int hashCode() {
        return username.hashCode() + email.hashCode();
    }
}

