BEGIN TRANSACTION;

DROP TABLE IF EXISTS amigo;

DROP TABLE IF EXISTS participa;

DROP TABLE IF EXISTS ganha;

DROP TABLE IF EXISTS joga;

DROP TABLE IF EXISTS compra;

DROP TABLE IF EXISTS mensagem;

DROP TABLE IF EXISTS cracha;

DROP TABLE IF EXISTS partida_multijogador;

DROP TABLE IF EXISTS partida_normal;

DROP TABLE IF EXISTS partida;

DROP TABLE IF EXISTS jogo_estatistica;

DROP TABLE IF EXISTS jogador_estatistica;

DROP TABLE IF EXISTS conversa;

DROP TABLE IF EXISTS jogo;

DROP TABLE IF EXISTS jogador CASCADE;

DROP TABLE IF EXISTS regiao;

DROP DOMAIN IF EXISTS alphanumeric CASCADE;

DROP DOMAIN IF EXISTS email CASCADE;

DROP DOMAIN IF EXISTS url CASCADE;

COMMIT;