DROP TABLE IF EXISTS mensagem;

DROP TABLE IF EXISTS conversa;

DROP TABLE IF EXISTS cracha;

DROP TABLE IF EXISTS partida_multijogador;

DROP TABLE IF EXISTS partida_normal;

DROP TABLE IF EXISTS partida;

DROP TABLE IF EXISTS jogo_estatistica;

DROP TABLE IF EXISTS jogo;

DROP TABLE IF EXISTS compra;

DROP TABLE IF EXISTS jogador_estatistica;

DROP TABLE IF EXISTS jogador;

DROP TABLE IF EXISTS regiao;